# Generated by Django 4.1.5 on 2023-05-30 18:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, upload_to='images/', verbose_name='Products upload image')),
                ('text', ckeditor.fields.RichTextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
